name: Build and Push
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy.yml'
      - 'Dockerfile.jdk'
      - 'Dockerfile.native-image'
      - 'Dockerfile.nodejs'
      - 'Dockerfile.python'
  workflow_dispatch:

env:
  QUAYIO_USERNAME: ${{ secrets.QUAYIO_USERNAME }}
  QUAYIO_TOKEN: ${{ secrets.QUAYIO_TOKEN }}

jobs:
  jdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile.jdk
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/graalvm-8:jdk
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

  native-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile.native-image
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/graalvm-8:native-image
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

  nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile.nodejs
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/graalvm-8:nodejs
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile.python
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/graalvm-8:python
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
